# Config file for automatic testing at travis-ci.org

sudo: false
language: python

python:
  - 3.5
  - 3.6
  - 3.7

install: pip install -r requirements_test.txt
script: tox -- --cov --cov-append
after_success: codecov
